if [ ! -L ~/.homeassistant ]; then
  ln -s /workspaces/home-assistant-minecraft-profile/config ~/.homeassistant
fi
if [ ! -L /workspaces/home-assistant-minecraft-profile/config/custom_components ]; then
  ln -s /workspaces/home-assistant-minecraft-profile/custom_components /workspaces/home-assistant-minecraft-profile/config/custom_components
fi
